### ISSUE TITLE
New article for genodians.org

### ISSUE THREAD

**Issue by valerius2k** [genodelabs/genodians.org#10]
I got network boot via PXE with getting logs via AMT SOL (via appropriate run tool backends) working on my Thinkpad and decided to share my experiences with it. So, I'd like to join genodians.org. Maybe, more articles will follow soon. My content is there: https://github.com/valerius2k/genodian.git. Please, use the name "valerius" as an author.

**Comment by valerius2k** [comment]
P.S.: My real name is Valery Sedletski

**Comment by valerius2k** [comment]
P.P.S.: Tested a static page generation via makefiles, It seems, it looks ok.

**Comment by nfeske** [comment]
Welcome to Genodians.org!

Your first article looks excellent.

Before going forward, may you change the file name of the article according to the current date so that the posting appears at the current top spot of the website? Right now, it would appear as if you published it on March 9.

**Comment by valerius2k** [comment]
Yes, that was the date when I wrote the article. OK, so changed the date  to March, 12.

**Comment by nfeske** [comment]
Thanks for the quick response. Commit https://github.com/genodelabs/genodians.org/commit/048c5a65ad3ea6fe1202b52da9160efc516361b8 adds you as author.

@cnuke Can you please update the image?

**Comment by valerius2k** [comment]
Thank you!

**Comment by cnuke** [comment]
Done.
