### ISSUE TITLE
No content updates after import subsystem exits

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genodians.org#12]
Every now and the it happens that new content is not shown on the website because some step of the content-update process has failed.

Under the hood, the content is generated by the import subsystem which uses the `sequence` component. This component will exit whenever one of the components in the sequence exits with an error. Since this is a problem when used in a scenario such as *genodians.org* it seems to be reasonable to extent the component so that it will attempt to restart the sequence from the beginning in case of an error.

I am not sure, though, if it is justified to add this functionality (for now it might be enough to just restart the sequence) or if it would be better to replace it by a small management component that knows the relation between the various steps and can take more appropiate actions.

**Comment by nfeske** [comment]
In general, I would prefer to base genodians on off-the-shelf components only, without any custom-written C++ code. This way, genodians can be taken as a blue print for web appliances for people who are not well versed with C++ or the Genode API. It is merely a composition of existing building blocks.

Following this line of thinking, the addition of a "keep-going" feature to the sequence tool looks more attractive to me than a custom C++ management component. Also, such a feature might become handy in other use cases of the sequence tool.

**Comment by cnuke** [comment]
I added the feature to the `sequence` component in https://github.com/cnuke/genode/commit/5ee314e9f80dcf764a17ccf1f5242c5d674ce871 and deployed it an *genodians.org*.

**Comment by cnuke** [comment]
The commit is in the Genode master branch for some time now, I'll close the issue.
