### ISSUE TITLE
New author Tomasz Gajewski

### ISSUE THREAD

**Issue by tomga** [genodelabs/genodians.org#14]
Please consider adding my repository https://github.com/tomga/genodian to http://genodians.org/

**Comment by nfeske** [comment]
Welcome to Genodians, Thomasz!

I added you as an author in 15489c850f450ef07eaff38c96ba0063031e4c8c.

@cnuke, would you please update the server image?

**Comment by tomga** [comment]
Wow, I passed without any corrections or maybe you didn't have time to check it? :-)

Also you made funny mistake with my name. Part is in german and part in polish. I haven't seen such combination earlier :-)

**Comment by nfeske** [comment]
> Wow, I passed without any corrections or maybe you didn't have time to check it? :-)

I only checked the formalities of your git repository and tested the integration. Everything, including the text markup, worked like a charm.

The content of the articles is entirely are entirely up to you. They are your's, and you are speaking as an individual, not for the project. If I see mistakes when reading, I'll of course give you a notice. But I'll wait with reading your article until it is online.

I took the spelling of your name from the title of this issue. Please let me know how exactly you want the name appear on the web site (defined at https://github.com/genodelabs/genodians.org/blob/master/authors/tomga/name). So I can adjust it according to your wishes.

**Comment by tomga** [comment]
Mistake is only in comment above.

> Welcome to Genodians, **Thomasz**!

Name in commit is ok. Sorry for the confusion. I didn't even notice, at that moment, that you added my name in your commit.

**Comment by cnuke** [comment]
@nfeske done.
