### ISSUE TITLE
Support for a standard markup language

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genodians.org#17]
I would write posts if I could use markdown. GOSH is a "not invented here" format with zero adoption outside Genode documentation, which is a red flag to outside contributors.

**Comment by skalk** [comment]
@ehmry: I can understand the argument that outside contributors would profit from the fact to use a more widespread markdown language than GOSH. But GOSH is not a "not invented here" format. That sounds like an unjustified criticism. In fact was written at a time, when jekyll and co. were not existent at all, long before the existence of the Genode OS framework.
We are used to GOSH and have a lot of documents written in it. Therefore, it would mean unproductive work to convert everything in a new language.
But, I would appreciate it to extend the genodians.org scenario by another standard language as alternative for outside contributors. That would mean to port the corresponding compiler, e.g., jekyll to Genode. Maybe, that is getting a low-hanging porting work as soon as the libc adaption (noux functionality inside libc) and SDK development are prospered further, which is what @nfeske currently drives forward.

**Comment by ehmry** [comment]
I stand corrected on the history of GOSH.

**Comment by ehmry** [comment]
Ok, stupid issue.
