### ISSUE TITLE
TTS blog

### ISSUE THREAD

**Issue by ttcoder** [genodelabs/genodians.org#2]
My real name: Cedric Degea

Repo: https://github.com/ttcoder/genodian/tree/master

Github won't let me edit "author.txt"; meant to add this line at bottom:
*Company* [https://www.tunetrackersystems.com - TuneTracker Systems LLC]

**Comment by nfeske** [comment]
Great to see you at genodians.org!

> Github won't let me edit "author.txt"; meant to add this line at bottom:

This message leaves me a bit confused. I wonder, are you trying to edit the content of your genodian repository directly on GitHub? I don't know if or how that works, but I recommend using the regular git work flow, editing content in your local clone of the repository, committing changes locally, and pushing those commits to github via `git push`.

**Comment by ttcoder** [comment]
You'd think it would work too of course :-) But yet I get an error as seen over at https://tts-genode.neocities.org/genode.html

Anyway we don't have to let us be stopped by that problem, I'll figure it out on my own. Crossing fingers hoping I'll be able to post and correct articles without problem. I won't mix web- and git-editing this time

**Comment by nfeske** [comment]
I think you have to tell `git commit` explicitly what you want to commit.

```
git commit author.txt
```

or 

```
git commit .
```

**Comment by ttcoder** [comment]
That was exactly it ! Commited and pushed.

**Comment by nfeske** [comment]
Does the static site generation work well for your test posting?

I assume that you don't want your test posting actually end up at genodians.org, right? Hence, once you add your first real posting, you should better remove your test posting again (git rm <file>). I'd appreciate a quick hint when your first posting is ready. So we can add you to the authors and update the web server accordingly. Can't wait to see you at genodians.org! :-)

**Comment by ttcoder** [comment]
Gotta spend time with the kids tonight, and tomorrow will be dedicated entirely to customer support (trouble with haiku's serial port stack.. again..). Maybe the day after tomorrow. Frustrating to me because the short "GUI basics" articles is ready to go, in HTML form.. I want to post it, you want to read it, just have to find the most precious commodity: *time* sigh

**Comment by nfeske** [comment]
It was not my intention to pressure you. ;-) Please take your time.

**Comment by ttcoder** [comment]
Pushed the "micro" blog, which turned out to be article length *g*; tested static gen, looks good; allowed me to fix some structure rendering problems.

We see eye to eye on this.. To be honest it feels good to be 'pressured' a bit -- in Haiku the guys were starting to be fed up with me and my endless stream of tickets, so it's nice to fell welcome again 8-).. That might be the subject of an article, "how micro kernels make the atmosphere/zeitgeist  more light-hearted because there are fewer bugs which are easier to fix" *grin*

**Comment by nfeske** [comment]
Fantastic! We need two minor tweaks still, for the consistency of the layout.

* You used the chapter markup (###) for the posting title. In GOSH, the document title is a centered piece of text instead. So you may change it as follows:
  
  ```
  -GUI basics
  -##########
  +
  +                        GUI basics
  ```

* The sections should be underlined with plain `---` characters (the markup for a named paragraph), not `===` characters. We should better not use GOSH's full document-structure markups (chapters, sections, sub sections) for the postings. That's a good point to add to the genodians.org README, actually.

**Comment by ttcoder** [comment]
Tested and pushed.

Took me a while to understand I cannot use tabs: no amount of tabs will be accepted, but a single space suffices to mark the title line. If the GOSH syntax is not to change on this, it probably makes sense to explicitely document this in the readme (or maybe it is there and I missed it)

Nice to be a 'published author' :-)

**Comment by nfeske** [comment]
That was quick! I added you as author in 836b956ee3d8be78c54be2f6f95f68c97cd9ad99 now. I'm quite a bit excited. :-)

@cnuke Could you please update the web server deployment?

> Took me a while to understand I cannot use tabs: no amount of tabs will be accepted, but a single space suffices to mark the title line. If the GOSH syntax is not to change on this, it probably makes sense to explicitely document this in the readme (or maybe it is there and I missed it)

The information is buried in the GOSH documentation at https://github.com/nfeske/gosh/blob/master/README#L144. BTW, I you prefer some decoration for the title, GOSH allows the use of `===` above and below of the title (that feature is actually missing in the README). For an example: https://github.com/genodelabs/genode/blob/master/doc/getting_started.txt

**Comment by nfeske** [comment]
Your first posting is online!

**Comment by nfeske** [comment]
@ttcoder Btw, I left a comment on your posting at reddit/r/genode - just in case you missed it. ;-)

**Comment by ttcoder** [comment]
Was monitoring the reddit page for a couple days after posting and saw it ;-)  But then the project sucked me back in and -- blam! Back in the black hole *g*

I had initially started editing a new article titled "gui basics: IPC" to build on your response, mentionning how drag'n'drop and app_server serving as "go between" between apps (inter-process) conceptually works in Haiku.. But now I think I'll have to post an article titled "the chronicles of gui-geek" *g* first, and the IPC one will come later.. Looks like this project involves a lot of "up front" coding, before seeing results; not too surprising really. Hopefully this means the downstream work will proceed faster, getting dividends from early work.

Anyway, this quick post just so you know I'm not dead *g*
(liked the new roadmap BTW!)

**Comment by nfeske** [comment]
@cnuke the server does not seem to pick up the new article. Can you have a look?

**Comment by nfeske** [comment]
As of now, only png files in the top-level directory are copied to the html directory (the selection of files happens at https://github.com/genodelabs/genodians.org/blob/master/Makefile#L64). I kept the mechanism so simple to avoid the need to add the `find` command to the site generator.

I wonder, did it work issuing `make` manually and opening html/index in the browser?

**Comment by ttcoder** [comment]
I had added a symlink in html/ to test locally..
So I fixed everything. Invoking "make" still won't copy the .png files though, neither in html/ttcoder/ nor in html/ .
Will commit anyway

My folder looks like this now:

....genodian-GitHub/genodian> ls
_blog.html                           2019-01-20-gui-chronicles.txt
_next                                author.png
_Template_2019-0x-0x-template.txt    author.txt
2019-01-09-gui-basics.txt            LICENSE
2019-01-20_Pulse-vs-pulse_small.png  README.md
2019-01-20_Pulse-vs-pulse.png

**Comment by ttcoder** [comment]
Refreshed genodians.org and it works now, thanks!
