### ISSUE TITLE
New genodian!

### ISSUE THREAD

**Issue by mickenx** [genodelabs/genodians.org#23]
https://github.com/mickenx/genodian

Name: Michael Grunditz.
Hope it will do!

**Comment by nfeske** [comment]
Very cool! I added you with commit b2b9f5309c96c0ba65277e42fb67728420296d42

@cnuke Could you please update the image on the web server?

**Comment by nfeske** [comment]
In your text, you are using several enumerations. It might be best to use the `#` markup for the numbered enumerations. You may take a look at  https://github.com/nfeske/genodian/blob/master/2021-09-20-pine-fun-pinephone-boot.txt#L122 as an example.

**Comment by cnuke** [comment]
@nfeske done. (Apparently github switched the “primary” branch to `main`, I adapted the zip URL accordingly.)

**Comment by nfeske** [comment]
@cnuke that was an oversight on my side. Thank you. Fixed with 7a2445c3e52c5a4f6d94a5b17471f402ae5bdf0e
