### ISSUE TITLE
Be more robust when a resource (author) is not available

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genodians.org#32]
While recently adding a new author to the _genodians.org_ appliance I noticed that some resources were temporarily not available. In this case the `fetchurl` exits with an error and the download step is triggered again (due to the way the `sequence` component that orchestrates the steps is configured I assume *), which in turn leads to not updating the website with new posts for this duration.

The following commits address this problem by allowing `fetchurl` to ignore any failures in its reporting and the Genodians.org's Makefile to ignore incomplete authors.

*) I have not checked yet if we can get a similar result by solely changing how the scenario operates.

**Comment by nfeske** [comment]
That looks good to me. Thanks for carrying this forward. It matches exactly what I remembered from our recent conversation.

**Comment by nfeske** [comment]
Let us merge the commits after the Genode 23.11 release is out of the door.

**Comment by nfeske** [comment]
Merged https://github.com/cnuke/genode/commit/09ade3c8d3c4bd287c7420bc9effb60fe26d790a to genode/staging.

**Comment by nfeske** [comment]
I also merged https://github.com/cnuke/genodians.org/commit/6c35da9473ca4aa2fef6cc06e2ea663ba431968a to the master branch of genodians.org now.

**Comment by cnuke** [comment]
Thanks for merging.
