### ISSUE TITLE
Inclusion of m-stein repository

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genodians.org#5]
I'd like to propose the inclusion of my repository https://github.com/m-stein/genodian.

**Comment by cnuke** [comment]
Done.

**Comment by nfeske** [comment]
@m-stein since your article appears to be from January 1st but your author was added just today, it appears somewhere down the timeline. Maybe it makes sense to rename the article file to have the current date, so that the article is shown at the top?

**Comment by m-stein** [comment]
Yep, have done this and added some content fixes. Thanks for the hint.

**Comment by cnuke** [comment]
Done but in the future we should not do that as the entry will be duplicated in RSS readers as the `<guid>` changes.

**Comment by m-stein** [comment]
Should it be online already? Haven't seen a change.

**Comment by cnuke** [comment]
You may have to forcefully flush your browser cache because the httpd returns always the same timestamp.
