### ISSUE TITLE
Inclusion of Daniel C.'s content

### ISSUE THREAD

**Issue by zorodc** [genodelabs/genodians.org#8]
I'd like to request the addition of my content, here: [https://github.com/zorodc/genodians](url)
At the moment there is just the one piece in there.

I have tried to follow the content format prescribed in the README
However, there aren't line breaks in the piece except to separate paragraphs, and I did use gosh's chapter feature once in order to have a postscript/footnotes section whose elements I could use bracketed references to refer to. If these things prove an issue, I can change them.

**Comment by nfeske** [comment]
Hey, it's fantastic to see you at genodians!

I just gave your article a quick try locally and encourage the following minor adjustments.

* The first paragraph of the article is shown on the front page as a summary. Right now, your article starts with the "Vorrede" paragraph, to the effect that the paragraph title appears on top of the whole item at the frontpage, and that the quote is used as summary. It may be sensible to prepend the entire article with a sentence that shortly outlines what the article is about. Please have a look at the existing articles to see how it works.
* If you want the quote stand out a little, you may wrap it with underscore characters at the beginning and end of the line. This way, the quota appears as italic text, which separates it well from the actual content.
* The article file need to renamed of course. I guess you added the prefixing and suffixing underscore to avoid accidentally publishing it?

The article is very fine read. Thank you for being so outspoken about your view. I very much appreciate your contribution!

**Comment by zorodc** [comment]
I'm glad you like it in its final form. I've renamed the article file, italicized the quotes, and added a little summary block. I actually put the underscores around the filename by mistake - I suppose I was a bit sleepy when moving the article to gosh by the end of it, and I interpreted the underscores around the gosh-formatted filename example in the README literally. I also made a few stylistic edits.

I built it on my local machine, and it seems to work. Feel free to verify that if you'd like.

**Comment by nfeske** [comment]
Superb! One last thing: Would you update the file name to the current date? With the date used right now (Feb 4), your posting would appear below my one from yesterday (Feb 5). But your posting deserves the top spot! ;-)

**Comment by zorodc** [comment]
Ah, of course. Done!

**Comment by nfeske** [comment]
@cnuke Now its your turn ;-)

**Comment by zorodc** [comment]
I've noticed it's now on genodians. I believe it now appropriate to close the issue.

**Comment by nfeske** [comment]
Yes, thanks for the splendid article.
